### ISSUE TITLE
some tests file leave stuff under /tmp

### ISSUE THREAD

**Issue by ghost** [Perl-Toolchain-Gang/YAML-Tiny#34]
Reported in dagolden/CPAN-Meta-YAML#2

**Comment by Leont** [comment]
> sounds like a good usecase for Test::TempDir::Tiny. :)

I don't really see what problem Test::TempDir::Tiny solves that can't be fixed with File::Temp. It adds complications that are not worth the advantages (of keeping the directory on failure).

**Comment by karenetheridge** [comment]
possibly the cause of http://www.nntp.perl.org/group/perl.perl5.porters/2015/03/msg226606.html

**Comment by karenetheridge** [comment]
let's try to get this released soon, since it is proving to be an annoyance.

**Comment by karenetheridge** [comment]
iirc the reason why I didn't release this right away was because I was stuck on getting inc::latest to work. but given the p5p problem, that shouldn't be a blocker.

**Comment by karenetheridge** [comment]
Released in verison 1.65.
