### ISSUE TITLE
CPAN-Meta-YAML/t/30_yaml_spec_tml.t produces noise on stderr

### ISSUE THREAD

**Issue by iabyn** [Perl-Toolchain-Gang/YAML-Tiny#38]
CPAN-Meta-YAML/t/30_yaml_spec_tml.t produces noise on stderr. This trivial diff fixes that.

diff --git a/cpan/CPAN-Meta-YAML/t/30_yaml_spec_tml.t b/cpan/CPAN-Meta-YAML/t/30
index 1209a96..3cd97b6 100644
--- a/cpan/CPAN-Meta-YAML/t/30_yaml_spec_tml.t
+++ b/cpan/CPAN-Meta-YAML/t/30_yaml_spec_tml.t
@@ -9,7 +9,7 @@ use TestUtils;
 my $JSON = json_class()
     or Test::More::plan skip_all => 'no JSON backends available!?';
 
-diag 'using JSON backend: ' . $JSON;
+note 'using JSON backend: ' . $JSON;
 
 # Each spec test will need a different bridge and arguments:
 my @spec_tests = (

**Comment by karenetheridge** [comment]
This output is intentional, for diagnostic purposes. What is the problem?

**Comment by dagolden** [comment]
More specifically, we want to see the JSON backend smoke reports, etc. if any tests fail.  Those are not run in verbose mode so we need `diag` instead of `note`.

Actually, we really ought to include `$VERSION` in that diag.

**Comment by karenetheridge** [comment]
I just figured out that @iabyn is Dave Mitchell, and this is part of the "make blead build quiety" quest.  What environment variable should we check for to skip this diag when being built in blead, as it's not going to be relevant there (the only backend available in core is JSON::PP)?

**Comment by dagolden** [comment]
PERL_CORE

**Comment by karenetheridge** [comment]
ok, PR #39 prepared to address both these points.
