### ISSUE TITLE
time to release CPAN-Meta-YAML from 1.68-TRIAL?

### ISSUE THREAD

**Issue by karenetheridge** [Perl-Toolchain-Gang/YAML-Tiny#42]
1.68-TRIAL has been out for a few weeks with no issues reported, and cpantesters is green. It's time to consider porting this to CPAN-Meta-YAML.

**Comment by dagolden** [comment]
You'll have to release YAML-Tiny stable, then I can ship CPAN-Meta-YAML

**Comment by dagolden** [comment]
CPAN-Meta-YAML-0.017-TRIAL.tar.gz released to CPAN

After it looks good, we can release stable.

**Comment by jkeenan** [comment]
http://search.cpan.org/~dagolden/CPAN-Meta-YAML-0.018/ was released to CPAN on 11 Dec 2015.

Is this ticket closable?
