### ISSUE TITLE
Can't parse META.yml from AnyEvent::AIO

### ISSUE THREAD

**Issue by robn** [Perl-Toolchain-Gang/YAML-Tiny#43]
META.yml from AnyEvent::AIO: https://api.metacpan.org/source/MLEHMANN/AnyEvent-AIO-1.1/META.yml

YAML::XS can handle it:

```
$ curl -s https://api.metacpan.org/source/MLEHMANN/AnyEvent-AIO-1.1/META.yml | perl -MYAML::XS -E 'local $/; Load(<>)'
```

YAML::Tiny and YAML cannot:

```
$ curl -s https://api.metacpan.org/source/MLEHMANN/AnyEvent-AIO-1.1/META.yml | perl -MYAML::Tiny -E 'local $/; Load(<>)' 
YAML::Tiny failed to classify line '{' at -e line 1.
```
```
$ curl -s https://api.metacpan.org/source/MLEHMANN/AnyEvent-AIO-1.1/META.yml | perl -MYAML -E 'local $/; Load(<>)' 
YAML Error: Expected separator '---'
   Code: YAML_PARSE_ERR_NO_SEPARATOR
   Line: 1
   Document: 2
 at /home/robn/perl5/perlbrew/perls/perl-5.20.0/lib/site_perl/5.20.1/YAML/Loader.pm line 78.
```

[RT#100983](https://rt.cpan.org/Public/Bug/Display.html?id=100983) suggests this is actually valid YAML, and YAML::Tiny might not be able to cope with it, so I'm filing this here.

This is a problem for `dh-make-perl`:
```
CPAN::Meta::YAML failed to classify line '{' at /usr/local/share/perl/5.14.2/Parse/CPAN/Meta.pm line 45.
 at /usr/local/share/perl/5.14.2/CPAN/Meta.pm line 300.
 at /usr/share/perl5/DhMakePerl/Command/Packaging.pm line 190.
```

If you didn't want to extend YAML::Tiny to handle this form, another option might be to have CPAN::META use YAML::XS if it's installed. I can easily arrange that on my build host. Let me know if that's preferable and I'll open an issue against that instead.

Of course, I'm assuming that this META.yml is actually valid. If it's not then it's a problem for the upstream author and I will take it up with them. Just let me know.

**Comment by karenetheridge** [comment]
My initial feeling here is that while JSON may be a valid subset of YAML, it is not parsable by YAML::Tiny/CPAN::Meta::YAML, and we should add documentation to CPAN::Meta::Spec clearly stating this.

cc @dagolden

**Comment by karenetheridge** [comment]
..so really, the author ought to put proper parsable YAML into META.yml.

He even wrote this: https://metacpan.org/pod/JSON::XS#JSON-and-YAML

**Comment by rjbs** [comment]
CPAN::Meta::Spec states:

> In the past, the distribution metadata structure had been packed with distributions as META.yml, a file in the YAML Tiny format (for which, see YAML::Tiny). Tools that consume distribution metadata from disk should be capable of loading META.yml, but should prefer META.json if both are found.

I'm not sure something more explicit is really required.

There was a brief push before we wrote the v2 spec to put JSON in the META.yml file, spearheaded by me, but a truce was declared with the introduction of META.json.  At any rate, it's odd that Marc would use JSON in META.yml given his [writings on the difficulty of one being substituted for the other].

I think the best solution here may be for dh-make-perl to use META.json when available!  Failing that, though, you should be able to set the environment variable `$PERL_YAML_BACKEND` to YAML::XS.  This will cause CPAN::Meta to use YAML::XS rather than CPAN::Meta::YAML.  The error you (@robn) provide above suggests that CPAN::Meta is being used in dh-make-perl, so I'd expect this to work.  Let me know if it doesn't.

One caveat, though:  CPAN::Meta::YAML allows one or two illegal constructs that YAML::XS will reject, such as duplicate keys.

**Comment by shadowcat-mst** [comment]
I just went and looked this up, and as of 2011, dh-make-perl uses META.json -

https://anonscm.debian.org/cgit/pkg-perl/packages/dh-make-perl.git/tree/lib/DhMakePerl/Command/Packaging.pm#n183

If you can install YAML::XS on the build host, presumably you can also install a version of dh-make-perl less than four years old, at which point the problem should go away.

**Comment by haarg** [comment]
The dist in question doesn't ship with a META.json though.

**Comment by shadowcat-mst** [comment]
Sure, it's going to require a re-make-dist to unfuck it or some other similar action. But that's between robn and MLEHMANN - if the dist was remotely reasonable, everything would work fine; exactly how to make the dist remotely reasonable is left as an exercise to the packager.

**Comment by karenetheridge** [comment]
> The dist in question doesn't ship with a META.json though.

That's exactly the point I was making here :) -- and the ultimate solution -- https://rt.cpan.org/Ticket/Display.html?id=100983#txn-1538254

I'm closing this ticket now as there isn't anything for YAML-Tiny or CPAN-Meta-YAML to do here.

**Comment by robn** [comment]
`PERL_YAML_BACKEND=YAML::XS` did the trick for this particular package.

I likely won't pursue this with upstream at the moment since it turns out I don't actually need this package - it was incorrectly listed as a requirement in another package, which has been fixed overnight.

Thanks for the help!
