### ISSUE TITLE
4. Syntax - YAML Tiny Character Stream typo

### ISSUE THREAD

**Issue by hatonthecat** [Perl-Toolchain-Gang/YAML-Tiny#61]
"If necessary, a document boundary should simply ~by~ indicated with a "---" marker, with not preceding "..." marker."
should be:
"If necessary, a document boundary should simply be indicated with a "---" marker, with not preceding "..." marker."

https://github.com/Perl-Toolchain-Gang/YAML-Tiny#4-syntax

**Comment by karenetheridge** [comment]
Thanks, applied and released.
